// src/components/chat/ConversationHistory.tsx
import type { Conversation } from "@/models/chat/conversation.models";
import { ConversationGroup } from "@/components/chat/ConversationGroup";

interface ConversationHistoryProps {
  conversations: Conversation[];
  activeConversationId: string;
  onSelectConversation: (id: string) => void;
}

export function ConversationHistory({
  conversations,
  activeConversationId,
  onSelectConversation,
}: ConversationHistoryProps) {
  if (conversations.length === 0) {
    return (
      <div className="chat-hist">
        <div className="chat-hist-label">Conversations</div>
        <p className="chat-hist-empty">Aucune conversation.</p>
      </div>
    );
  }

  return (
    <div className="chat-hist">
      <ConversationGroup
        label="Conversations"
        conversations={conversations}
        activeConversationId={activeConversationId}
        onSelectConversation={onSelectConversation}
      />
    </div>
  );
}

// src/components/chat/ConversationHistory.vue
<script setup>
import ConversationGroup from "@/components/chat/ConversationGroup.vue";

defineProps({
  conversations: { type: Array, required: true },
  activeConversationId: { type: String, required: true },
});

defineEmits(["select-conversation"]);
</script>

<template>
  <div class="chat-hist">
    <template v-if="conversations.length === 0">
      <div class="chat-hist-label">Conversations</div>
      <p class="chat-hist-empty">Aucune conversation.</p>
    </template>
    <ConversationGroup
      v-else
      label="Conversations"
      :conversations="conversations"
      :active-conversation-id="activeConversationId"
      @select-conversation="$emit('select-conversation', $event)"
    />
  </div>
</template>
