// src/components/chat/ConversationSidebar.vue
<script setup>
import CartinLogo from "@/components/common/CartinLogo.vue";
import NewConversationButton from "@/components/chat/NewConversationButton.vue";
import ConversationHistory from "@/components/chat/ConversationHistory.vue";
import UserProfile from "@/components/chat/UserProfile.vue";

defineProps({
  conversations: { type: Array, required: true },
  activeConversationId: { type: String, required: true },
  isOpen: { type: Boolean, default: false },
});

defineEmits(["new-conversation", "select-conversation", "logout"]);
</script>

<template>
  <aside :class="['chat-sidebar', isOpen ? 'open' : '']">
    <div class="chat-side-brand">
      <CartinLogo :width="128" />
      <div class="chat-side-tag">Assistant conversationnel</div>
    </div>
    <NewConversationButton @click="$emit('new-conversation')" />
    <ConversationHistory
      :conversations="conversations"
      :active-conversation-id="activeConversationId"
      @select-conversation="$emit('select-conversation', $event)"
    />
    <UserProfile @logout="$emit('logout')" />
  </aside>
</template>

// src/components/chat/ConversationSidebar.tsx
import type { Conversation } from "@/models/chat/conversation.models";
import { CartinLogo } from "@/components/common/CartinLogo";
import { NewConversationButton } from "@/components/chat/NewConversationButton";
import { ConversationHistory } from "@/components/chat/ConversationHistory";
import { UserProfile } from "@/components/chat/UserProfile";

interface ConversationSidebarProps {
  conversations: Conversation[];
  activeConversationId: string;
  isOpen?: boolean;
  onNewConversation: () => void;
  onSelectConversation: (id: string) => void;
  onLogout: () => void;
}

export function ConversationSidebar({
  conversations,
  activeConversationId,
  isOpen = false,
  onNewConversation,
  onSelectConversation,
  onLogout,
}: ConversationSidebarProps) {
  return (
    <aside className={`chat-sidebar${isOpen ? " open" : ""}`}>
      <div className="chat-side-brand">
        <CartinLogo width={128} />
        <div className="chat-side-tag">Assistant conversationnel</div>
      </div>
      <NewConversationButton onClick={onNewConversation} />
      <ConversationHistory
        conversations={conversations}
        activeConversationId={activeConversationId}
        onSelectConversation={onSelectConversation}
      />
      <UserProfile onLogout={onLogout} />
    </aside>
  );
}
