// src/components/chat/ConversationGroup.vue
<script setup>
import ConversationItem from "@/components/chat/ConversationItem.vue";

defineProps({
  label: { type: String, required: true },
  conversations: { type: Array, required: true },
  activeConversationId: { type: String, required: true },
});

defineEmits(["select-conversation"]);
</script>

<template>
  <div class="chat-hist-label">{{ label }}</div>
  <ConversationItem
    v-for="conversation in conversations"
    :key="conversation.id"
    :conversation="conversation"
    :active="conversation.id === activeConversationId"
    @select="$emit('select-conversation', $event)"
  />
</template>

// src/components/chat/ConversationGroup.tsx
import type { Conversation } from "@/models/chat/conversation.models";
import { ConversationItem } from "@/components/chat/ConversationItem";

interface ConversationGroupProps {
  label: string;
  conversations: Conversation[];
  activeConversationId: string;
  onSelectConversation: (id: string) => void;
}

export function ConversationGroup({
  label,
  conversations,
  activeConversationId,
  onSelectConversation,
}: ConversationGroupProps) {
  return (
    <>
      <div className="chat-hist-label">{label}</div>
      {conversations.map((conversation) => (
        <ConversationItem
          key={conversation.id}
          conversation={conversation}
          active={conversation.id === activeConversationId}
          onSelect={onSelectConversation}
        />
      ))}
    </>
  );
}
