// src/components/chat/MessageList.vue
<script setup>
import { toRefs } from "vue";
import MessageBubble from "@/components/chat/MessageBubble.vue";
import WelcomeScreen from "@/components/chat/WelcomeScreen.vue";
import TypingIndicator from "@/components/chat/TypingIndicator.vue";
import { useChatAutoScroll } from "@/composables/chat/useChatAutoScroll.js";

const props = defineProps({
  messages: { type: Array, required: true },
  isSending: { type: Boolean, required: true },
  suggestionsDisabled: { type: Boolean, default: false },
});

defineEmits(["select-suggestion", "retry"]);

const { messages, isSending } = toRefs(props);
const { endElement } = useChatAutoScroll(messages, isSending);
</script>

<template>
  <div class="chat-thread" :aria-busy="isSending">
    <div class="chat-thread-inner">
      <WelcomeScreen
        v-if="messages.length === 0"
        :disabled="suggestionsDisabled || isSending"
        @select-suggestion="$emit('select-suggestion', $event)"
      />
      <template v-else>
        <MessageBubble
          v-for="message in messages"
          :key="message.id"
          :message="message"
          @retry="$emit('retry', $event)"
        />
        <article v-if="isSending" class="chat-msg bot">
          <div class="chat-av-bot">AI</div>
          <div class="chat-bubble">
            <div class="chat-who">Cartin AI</div>
            <div class="chat-body">
              <TypingIndicator />
            </div>
          </div>
        </article>
      </template>
      <div ref="endElement" />
    </div>
  </div>
</template>

// src/components/chat/MessageList.tsx
import { useEffect, useRef } from "react";
import type { ChatMessage } from "@/models/chat/message.models";
import { MessageBubble } from "@/components/chat/MessageBubble";
import { WelcomeScreen } from "@/components/chat/WelcomeScreen";
import { TypingIndicator } from "@/components/chat/TypingIndicator";

interface MessageListProps {
  messages: ChatMessage[];
  isSending: boolean;
  suggestionsDisabled?: boolean;
  onSelectSuggestion: (question: string) => void;
  onRetryMessage?: (messageId: string) => void;
}

export function MessageList({
  messages,
  isSending,
  suggestionsDisabled = false,
  onSelectSuggestion,
  onRetryMessage,
}: MessageListProps) {
  const endRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, isSending]);

  return (
    <div className="chat-thread" aria-busy={isSending}>
      <div className="chat-thread-inner">
        {messages.length === 0 ? (
          <WelcomeScreen
            onSelectSuggestion={onSelectSuggestion}
            disabled={suggestionsDisabled || isSending}
          />
        ) : (
          <>
            {messages.map((message) => (
              <MessageBubble
                key={message.id}
                message={message}
                onRetry={onRetryMessage}
              />
            ))}
            {isSending ? (
              <article className="chat-msg bot">
                <div className="chat-av-bot">AI</div>
                <div className="chat-bubble">
                  <div className="chat-who">Cartin AI</div>
                  <div className="chat-body">
                    <TypingIndicator />
                  </div>
                </div>
              </article>
            ) : null}
          </>
        )}
        <div ref={endRef} />
      </div>
    </div>
  );
}
