// src/components/chat/MessageActions.vue
<script setup>
import { ref } from "vue";

const props = defineProps({
  content: { type: String, required: true },
});

const helpful = ref(false);
const copied = ref(false);

async function handleCopy() {
  await navigator.clipboard.writeText(props.content);
  copied.value = true;
  setTimeout(() => {
    copied.value = false;
  }, 1200);
}
</script>

<template>
  <div class="chat-msg-actions">
    <button type="button" title="Copier le message" @click="handleCopy">
      {{ copied ? "Copié" : "Copier" }}
    </button>
    <button
      type="button"
      title="Réponse utile"
      :aria-pressed="helpful"
      @click="helpful = !helpful"
    >
      {{ helpful ? "Utile ✓" : "Utile" }}
    </button>
  </div>
</template>

// src/components/chat/MessageActions.tsx
import { useState } from "react";

interface MessageActionsProps {
  content: string;
}

export function MessageActions({ content }: MessageActionsProps) {
  const [helpful, setHelpful] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 1200);
  };

  return (
    <div className="chat-msg-actions">
      <button type="button" title="Copier le message" onClick={() => void handleCopy()}>
        {copied ? "Copié" : "Copier"}
      </button>
      <button
        type="button"
        title="Réponse utile"
        aria-pressed={helpful}
        onClick={() => setHelpful((prev) => !prev)}
      >
        {helpful ? "Utile ✓" : "Utile"}
      </button>
    </div>
  );
}
