// src/components/chat/SuggestionCard.vue
<script setup>
defineProps({
  title: { type: String, required: true },
  description: { type: String, required: true },
  disabled: { type: Boolean, default: false },
});

defineEmits(["select"]);
</script>

<template>
  <button
    class="chat-sug"
    type="button"
    :disabled="disabled"
    @click="$emit('select', title)"
  >
    <strong>{{ title }}</strong>
    <span>{{ description }}</span>
  </button>
</template>

// src/components/chat/SuggestionCard.tsx
interface SuggestionCardProps {
  title: string;
  description: string;
  onSelect: (question: string) => void;
  disabled?: boolean;
}

export function SuggestionCard({
  title,
  description,
  onSelect,
  disabled = false,
}: SuggestionCardProps) {
  return (
    <button
      className="chat-sug"
      type="button"
      disabled={disabled}
      onClick={() => onSelect(title)}
    >
      <strong>{title}</strong>
      <span>{description}</span>
    </button>
  );
}
