// src/components/chat/SuggestionList.vue
<script setup>
import { CHAT_SUGGESTIONS } from "@/constants/chat.constants.js";
import SuggestionCard from "@/components/chat/SuggestionCard.vue";

defineProps({
  disabled: { type: Boolean, default: false },
});

defineEmits(["select"]);
</script>

<template>
  <div class="chat-suggestions">
    <SuggestionCard
      v-for="suggestion in CHAT_SUGGESTIONS"
      :key="suggestion.title"
      :title="suggestion.title"
      :description="suggestion.description"
      :disabled="disabled"
      @select="$emit('select', $event)"
    />
  </div>
</template>

// src/components/chat/SuggestionList.tsx
import { CHAT_SUGGESTIONS } from "@/constants/chat.constants";
import { SuggestionCard } from "@/components/chat/SuggestionCard";

interface SuggestionListProps {
  onSelect: (question: string) => void;
  disabled?: boolean;
}

export function SuggestionList({ onSelect, disabled = false }: SuggestionListProps) {
  return (
    <div className="chat-suggestions">
      {CHAT_SUGGESTIONS.map((suggestion) => (
        <SuggestionCard
          key={suggestion.title}
          title={suggestion.title}
          description={suggestion.description}
          onSelect={onSelect}
          disabled={disabled}
        />
      ))}
    </div>
  );
}
