// src/pages/auth/AuthPage.vue
<script setup>
import { computed, ref, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import { storeToRefs } from "pinia";
import AuthLayout from "@/layouts/AuthLayout.vue";
import AuthCard from "@/components/auth/AuthCard.vue";
import { useAuthStore } from "@/stores/auth.js";

const route = useRoute();
const router = useRouter();
const authStore = useAuthStore();
const { isSubmitting, error, success } = storeToRefs(authStore);

const mode = ref(route.query.mode === "access" ? "access" : "login");

watch(
  () => route.query.mode,
  (value) => {
    mode.value = value === "access" ? "access" : "login";
  },
);

function handleModeChange(nextMode) {
  authStore.clearFeedback();
  mode.value = nextMode;
  router.replace(nextMode === "login" ? { path: "/login" } : { path: "/login", query: { mode: "access" } });
}

async function handleLogin(values) {
  const loggedIn = await authStore.submitLogin(values);

  if (!loggedIn) {
    return;
  }

  const redirect =
    typeof route.query.redirect === "string"
      ? route.query.redirect
      : null;

  if (redirect) {
    await router.push(redirect);
    return;
  }

  await router.push({ name: "chat" });
}

async function handleForgotPassword(email) {
  await authStore.submitPasswordReset(email);
}

async function handleAccessRequest(values) {
  return authStore.submitAccessRequest(values);
}

const feedbackError = computed(() => error.value);
const feedbackSuccess = computed(() => success.value);
</script>

<template>
  <AuthLayout>
    <AuthCard
      :mode="mode"
      :error="feedbackError"
      :success="feedbackSuccess"
      :is-submitting="isSubmitting"
      @mode-change="handleModeChange"
      @login="handleLogin"
      @google-login="handleGoogleLogin"
      @forgot-password="handleForgotPassword"
      @access-request="handleAccessRequest"
    />
  </AuthLayout>
</template>

// src/pages/auth/AuthPage.tsx
import { useEffect, useMemo } from "react";
import { useSearchParams } from "react-router-dom";
import { AuthLayout } from "@/layouts/AuthLayout";
import { AuthCard } from "@/components/auth/AuthCard";
import { useAuthMode } from "@/hooks/auth/useAuthMode";
import { useLogin } from "@/hooks/auth/useLogin";
import { useAccessRequest } from "@/hooks/auth/useAccessRequest";
import type { AuthMode } from "@/models/auth";
import type { LoginFormValues } from "@/schemas/login";
import type { AccessRequestFormValues } from "@/schemas/access_request";

function parseMode(value: string | null): AuthMode {
  return value === "access" ? "access" : "login";
}

export function AuthPage() {
  const [searchParams, setSearchParams] = useSearchParams();
  const initialMode = useMemo(
    () => parseMode(searchParams.get("mode")),
    [searchParams],
  );
  const { mode, setMode } = useAuthMode(initialMode);
  const login = useLogin();
  const access = useAccessRequest();

  useEffect(() => {
    setMode(parseMode(searchParams.get("mode")));
  }, [searchParams, setMode]);

  const handleModeChange = (next: AuthMode) => {
    login.clearFeedback();
    access.clearFeedback();
    setMode(next);
    setSearchParams(next === "login" ? {} : { mode: next }, { replace: true });
  };

  const handleLogin = async (values: LoginFormValues) => {
    await login.submitLogin(values);
  };

  const handleAccess = async (values: AccessRequestFormValues) => {
    return access.submitAccessRequest(values);
  };

  const error = mode === "login" ? login.error : access.error;
  const success = mode === "login" ? login.success : access.success;
  const isSubmitting =
    mode === "login" ? login.isSubmitting : access.isSubmitting;

  return (
    <AuthLayout>
      <AuthCard
        mode={mode}
        onModeChange={handleModeChange}
        error={error}
        success={success}
        isSubmitting={isSubmitting}
        onLogin={handleLogin}
        onGoogleLogin={login.submitGoogleLogin}
        onForgotPassword={login.submitPasswordReset}
        onAccessRequest={handleAccess}
      />
    </AuthLayout>
  );
}
