// src/pages/chat/ChatPage.tsx
import { useMemo, useState } from "react";
import { ChatLayout } from "@/layouts/ChatLayout";
import { ConversationSidebar } from "@/components/chat/ConversationSidebar";
import { ChatHeader } from "@/components/chat/ChatHeader";
import { MessageList } from "@/components/chat/MessageList";
import { ChatComposer } from "@/components/chat/ChatComposer";
import { useChat } from "@/hooks/chat/useChat";
import { useChatComposer } from "@/hooks/chat/useChatComposer";
import { useSidebar } from "@/hooks/chat/useSidebar";
import type { Conversation } from "@/models/chat/conversation.models";

export function ChatPage() {
  const [shareInfo, setShareInfo] = useState<string | null>(null);
  const {
    messages,
    sessionId,
    isSending,
    error,
    sendMessage,
    retryMessage,
    startNewConversation,
    clearError,
  } = useChat();
  const { isSidebarOpen, openSidebar, closeSidebar, closeOnMobile } = useSidebar();

  const composer = useChatComposer({
    onSubmitMessage: async (message) => {
      await sendMessage(message);
    },
  });

  const conversations = useMemo<Conversation[]>(() => {
    if (!sessionId && messages.length === 0) return [];
    const title =
      messages.find((message) => message.role === "user")?.content.slice(0, 42) ||
      "Conversation en cours";
    return [
      {
        id: sessionId ?? "pending",
        title: title.length > 42 ? `${title}…` : title,
        messages,
        status: "active",
        createdAt: messages[0]?.createdAt ?? new Date().toISOString(),
        updatedAt: messages[messages.length - 1]?.createdAt ?? new Date().toISOString(),
      },
    ];
  }, [messages, sessionId]);

  const canShare = typeof window !== "undefined";

  const handleShare = async () => {
    if (!canShare) return;
    await navigator.clipboard.writeText(window.location.href);
    setShareInfo("Lien copié");
    setTimeout(() => setShareInfo(null), 1400);
  };

  const handleNewConversation = () => {
    startNewConversation();
    clearError();
    composer.focus();
    closeOnMobile();
  };

  const handleSuggestion = async (question: string) => {
    if (isSending) return;
    await sendMessage(question);
    composer.focus();
  };

  return (
    <ChatLayout
      isSidebarOpen={isSidebarOpen}
      onCloseSidebar={closeSidebar}
      sidebar={
        <ConversationSidebar
          conversations={conversations}
          activeConversationId={sessionId ?? "pending"}
          isOpen={isSidebarOpen}
          onNewConversation={handleNewConversation}
          onSelectConversation={() => closeOnMobile()}
          onLogout={() => setShareInfo("Authentification non connectée")}
        />
      }
      header={
        <ChatHeader
          onOpenSidebar={openSidebar}
          onShare={() => void handleShare()}
          canShare={canShare}
        />
      }
      composer={
        <ChatComposer
          value={composer.value}
          isBusy={isSending}
          liveDataEnabled={composer.liveDataEnabled}
          analysisEnabled={composer.analysisEnabled}
          textareaRef={composer.textareaRef}
          onChange={composer.handleChange}
          onSubmit={() => void composer.submit()}
          onKeyDown={(event) => void composer.onKeyDown(event)}
          onToggleLiveData={() => composer.setLiveDataEnabled((prev) => !prev)}
          onToggleAnalysis={() => composer.setAnalysisEnabled((prev) => !prev)}
        />
      }
    >
      <MessageList
        messages={messages}
        isSending={isSending}
        suggestionsDisabled={isSending}
        onSelectSuggestion={(question) => void handleSuggestion(question)}
        onRetryMessage={(messageId) => void retryMessage(messageId)}
      />
      {error ? (
        <div className="chat-toast" role="alert">
          {error}
        </div>
      ) : null}
      {shareInfo ? <div className="chat-toast">{shareInfo}</div> : null}
    </ChatLayout>
  );
}

// src/pages/chat/ChatPage.vue
<script setup>
import { computed, ref } from "vue";
import { storeToRefs } from "pinia";
import ChatLayout from "@/layouts/ChatLayout.vue";
import ConversationSidebar from "@/components/chat/ConversationSidebar.vue";
import ChatHeader from "@/components/chat/ChatHeader.vue";
import MessageList from "@/components/chat/MessageList.vue";
import ChatComposer from "@/components/chat/ChatComposer.vue";
import { useChatStore } from "@/stores/chat.js";
import { useUiStore } from "@/stores/ui.js";
import { useChatComposer } from "@/composables/chat/useChatComposer.js";

const chatStore = useChatStore();
const uiStore = useUiStore();

const { messages, sessionId, isSending, error } = storeToRefs(chatStore);
const { isSidebarOpen } = storeToRefs(uiStore);

const shareInfo = ref(null);

const {
  message,
  textareaRef,
  liveDataEnabled,
  analysisEnabled,
  handleInput,
  submit,
  handleKeydown,
  toggleLiveData,
  toggleAnalysis,
  focus,
} = useChatComposer((question) => chatStore.sendMessage(question));

const conversations = computed(() => {
  if (!sessionId.value && messages.value.length === 0) return [];
  const firstUser = messages.value.find((message) => message.role === "user");
  const title = firstUser?.content.slice(0, 42) || "Conversation en cours";
  return [
    {
      id: sessionId.value ?? "pending",
      title: title.length > 42 ? `${title}…` : title,
      messages: messages.value,
      status: "active",
      createdAt: messages.value[0]?.createdAt ?? new Date().toISOString(),
      updatedAt:
        messages.value[messages.value.length - 1]?.createdAt ??
        new Date().toISOString(),
    },
  ];
});

const canShare = typeof window !== "undefined";

async function handleShare() {
  if (!canShare) return;
  await navigator.clipboard.writeText(window.location.href);
  shareInfo.value = "Lien copié";
  setTimeout(() => {
    shareInfo.value = null;
  }, 1400);
}

function handleNewConversation() {
  chatStore.startNewConversation();
  chatStore.clearError();
  focus();
  uiStore.closeOnMobile();
}

async function handleSuggestion(question) {
  if (isSending.value) return;
  await chatStore.sendMessage(question);
  focus();
}
</script>

<template>
  <ChatLayout :is-sidebar-open="isSidebarOpen" @close-sidebar="uiStore.closeSidebar">
    <template #sidebar>
      <ConversationSidebar
        :conversations="conversations"
        :active-conversation-id="sessionId ?? 'pending'"
        :is-open="isSidebarOpen"
        @new-conversation="handleNewConversation"
        @select-conversation="uiStore.closeOnMobile"
        @logout="shareInfo = 'Authentification non connectée'"
      />
    </template>

    <template #header>
      <ChatHeader
        :can-share="canShare"
        @open-sidebar="uiStore.openSidebar"
        @share="handleShare"
      />
    </template>

    <MessageList
      :messages="messages"
      :is-sending="isSending"
      :suggestions-disabled="isSending"
      @select-suggestion="handleSuggestion"
      @retry="chatStore.retryMessage"
    />

    <div v-if="error" class="chat-toast" role="alert">{{ error }}</div>
    <div v-if="shareInfo" class="chat-toast">{{ shareInfo }}</div>

    <template #composer>
      <ChatComposer
        v-model="message"
        :is-sending="isSending"
        :live-data-enabled="liveDataEnabled"
        :analysis-enabled="analysisEnabled"
        :textarea-ref="textareaRef"
        @input="handleInput"
        @submit="submit"
        @keydown="handleKeydown"
        @toggle-live-data="toggleLiveData"
        @toggle-analysis="toggleAnalysis"
      />
    </template>
  </ChatLayout>
</template>
