// src/layouts/ChatLayout.tsx
import type { ReactNode } from "react";

interface ChatLayoutProps {
  sidebar: ReactNode;
  header: ReactNode;
  composer: ReactNode;
  children: ReactNode;
  isSidebarOpen: boolean;
  onCloseSidebar: () => void;
}

export function ChatLayout({
  sidebar,
  header,
  composer,
  children,
  isSidebarOpen,
  onCloseSidebar,
}: ChatLayoutProps) {
  return (
    <div className="chat-shell">
      {sidebar}
      <button
        className={`chat-backdrop${isSidebarOpen ? " on" : ""}`}
        type="button"
        aria-label="Fermer le menu latéral"
        onClick={onCloseSidebar}
      />
      <main className="chat-main">
        {header}
        {children}
        {composer}
      </main>
    </div>
  );
}

// src/layouts/ChatLayout.vue
<script setup>
defineProps({
  isSidebarOpen: { type: Boolean, required: true },
});

defineEmits(["close-sidebar"]);
</script>

<template>
  <div class="chat-shell">
    <slot name="sidebar" />
    <button
      :class="['chat-backdrop', isSidebarOpen ? 'on' : '']"
      type="button"
      aria-label="Fermer le menu latéral"
      @click="$emit('close-sidebar')"
    />
    <main class="chat-main">
      <slot name="header" />
      <slot />
      <slot name="composer" />
    </main>
  </div>
</template>
