// src/components/auth/AuthFeedback.vue
<script setup>
import AppAlert from "@/components/common/AppAlert.vue";

defineProps({
  error: { type: String, default: "" },
  success: { type: String, default: "" },
});
</script>

<template>
  <AppAlert v-if="error" type="error" :message="error" />
  <AppAlert v-else-if="success" type="success" :message="success" />
</template>

// src/components/auth/AuthFeedback.tsx
import { Alert } from "@/components/common/Alert";

interface AuthFeedbackProps {
  error?: string | null;
  success?: string | null;
}

export function AuthFeedback({ error, success }: AuthFeedbackProps) {
  if (error) {
    return <Alert type="error" message={error} />;
  }
  if (success) {
    return <Alert type="success" message={success} />;
  }
  return null;
}
